### PR TITLE
Cleaner Syntax

### PR DESCRIPTION
**Pull request by fabioespinosa**
I don't know if you knew this little trick, or just preferred to do the whole mapDispatchToProps. But you can do it in a cleaner syntax this way. Please feel free to reject the PR if you did this consciously.

### CODE REVIEW

**Comment by greglobinski** [comment]
Deploy preview for *jovial-mclean-88c629* ready!

Built with commit 291226758edbc073d7faff3b22df850f729ab079

https://deploy-preview-9--jovial-mclean-88c629.netlify.com

**Comment by greglobinski** [comment]
Thank you @fabioespinosa for the suggestion, however I will stay with the original.
First: just for consistency, that's not the only file where  `mapDispatchToProps` is used.
Second: I like your clear syntax, but I do not like the way you use an object literal directly as a `connect` parameter. I would rather use your syntax to define `const mapDispatchToProps` and only then pass it to `connect` as it is now.
but again,  thanks

**Comment by fabioespinosa** [comment]
No problem man, I get your point. Awesome work with the starter!

**Comment by greglobinski** [comment]
Hey @fabioespinosa, I use your syntax in my newest Gatsby starter https://github.com/greglobinski/gatsby-starter-personal-blog

**Comment by fabioespinosa** [comment]
Wow @greglobinski awesome job with that starter, congrats! 💯 Looks like you're right in the sweet spot between being a designer and a developer, awesome ux and ui!

Any reason why switching to JSS and not keeping styled-components?

**Comment by greglobinski** [comment]
Thank you @fabioespinosa 

Some reasons:
1. I use Material UI v1.0.0 (still in beta) in the starter and it is built with JSS, so I decided to stay with one syntax. 
2. After some experience with styled-components I feel that I do not like the way in which styled-components makes everything a component. With styled-components when I look at my `render()` function I do not see what is `<p>` and what is `<div>`, to know that I have to find the styled-component definitions.
3. Using components props inside css definitions are easier with JSS (react-jss)
4. Just to try something new. With the next starter I think I will use https://emotion.sh/

**Comment by fabioespinosa** [comment]
Hey @greglobinski sorry for late reply, I see, I've also seen emotion, want to try that too soon.

Just saw your gatsby-starter-mini-catalog, congrats again! will use it to make presentations!

**Pull request closed without merging**
